### ISSUE TITLE
Fix Header Dark Mode and Mobile

### ISSUE THREAD

**Issue by gokhanozdemir** [deniz-9/Olimpos#1]
https://github.com/deniz-9/Olimpos/blob/62f463e5f56e32b86fd39a1b59fb630a9e4e21c6/src/layouts/Header.jsx#L9

- [x] Dark Mode konusunda bir kaç antipattern gördüm. Örn header'da neden iki farklı component oluşturdun? 
[Tailwind Dark Mode docs](https://tailwindcss.com/docs/dark-mode)
- [x] Mobile header alanında mobilde görünmemesi gereken alanları gizleyebilirsin. `className="hidden sm:block"` gibi

**Comment by gokhanozdemir** [comment]
128px padding-x ![Image](https://github.com/user-attachments/assets/dfb41f6b-e174-4afc-8aaf-4e0ecd530289)

**Comment by gokhanozdemir** [comment]
@deniz-9 
https://tailwindcss.com/docs/container
Anlamadığın yerler olursa yeniden bakalım. Burada başka video bulamadım. Yine konuyu netleştirmezsen bakalım. https://www.youtube.com/watch?v=dOM78mzeBsQ

**Comment by deniz-9** [comment]
@gokhanozdemir  Dark ve Light  bileşenlerinde, dark iletişim bilgilerini, light ise menü başlıklarını içeriyor hocam.  Dark mode özelliği değiller. Ben ayırt etmek için bu şekilde adlandırdım.  Mobil görünüm için bir sidebar bileşeni oluşturdum. Bu sayede mobil versiyonda, ilgili alanlarda açılıp kapanan bir panel bulunuyor, böylece gereksiz bilgiler gözükmüyor.
